### ISSUE TITLE
Error during Catalyst init in a test project

### ISSUE THREAD

**Issue by kraifpatrik** [GameMakerHub/Catalyst#15]
I've tried to use Catalyst in an empty testing project and I've got an error during `catalyst init`. This is the full log from CMD:

```
PS C:\Users\kraif\OneDrive\Dokumenty\GameMakerStudio2\CatalystTest> catalyst init
Please enter the name of your package, in "vendor/package" format: kraifpatrik/test
Optionally enter the description for your package (max 255): Test
Please select the license
  [0 ] MIT
  [1 ] Apache-2.0
  [2 ] BSD-2-Clause
  [3 ] BSD-3-Clause
  [4 ] BSD-4-Clause
  [5 ] GPL-2.0-only
  [6 ] GPL-2.0-or-later
  [7 ] GPL-3.0-only
  [8 ] GPL-3.0-or-later
  [9 ] LGPL-2.1-only
  [10] LGPL-2.1-or-later
  [11] LGPL-3.0-only
  [12] LGPL-3.0-or-later
  [13] proprietary
 > 0
Please enter URL of your repository (optional): []
Please enter YYP file name: [CatalystTest.yyp]
PHP Fatal error:  Uncaught TypeError: Argument 4 passed to Catalyst\Service\CatalystService::createNew() must be of the type string, null given, called in C:\Program Files (x86)\GameMakerHub\Catalyst\src\Command\InitCommand.php on line 127 and defined in C:\Program Files (x86)\GameMakerHub\Catalyst\src\Service\CatalystService.php:14
Stack trace:
#0 C:\Program Files (x86)\GameMakerHub\Catalyst\src\Command\InitCommand.php(127): Catalyst\Service\CatalystService->createNew('kraifpatrik/tes...', 'Test', 'MIT', NULL, 'CatalystTest.yy...')
#1 C:\Program Files (x86)\GameMakerHub\Catalyst\vendor\symfony\console\Command\Command.php(255): Catalyst\Command\InitCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 C:\Program Files (x86)\GameMakerHub\Catalyst\vendor\symfony\console\Application.php(908): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 C:\Program  in C:\Program Files (x86)\GameMakerHub\Catalyst\src\Service\CatalystService.php on line 14

Fatal error: Uncaught TypeError: Argument 4 passed to Catalyst\Service\CatalystService::createNew() must be of the type string, null given, called in C:\Program Files (x86)\GameMakerHub\Catalyst\src\Command\InitCommand.php on line 127 and defined in C:\Program Files (x86)\GameMakerHub\Catalyst\src\Service\CatalystService.php:14
Stack trace:
#0 C:\Program Files (x86)\GameMakerHub\Catalyst\src\Command\InitCommand.php(127): Catalyst\Service\CatalystService->createNew('kraifpatrik/tes...', 'Test', 'MIT', NULL, 'CatalystTest.yy...')
#1 C:\Program Files (x86)\GameMakerHub\Catalyst\vendor\symfony\console\Command\Command.php(255): Catalyst\Command\InitCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 C:\Program Files (x86)\GameMakerHub\Catalyst\vendor\symfony\console\Application.php(908): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 C:\Program  in C:\Program Files (x86)\GameMakerHub\Catalyst\src\Service\CatalystService.php on line 14
```

**Comment by RobQuistNL** [comment]
Working on it 👍
